package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ActiveState generated by hbm2java
 */
public class ActiveState  implements java.io.Serializable {


     private Integer idactiveState;
     private String stateType;
     private Set reports = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set users = new HashSet(0);
     private Set products = new HashSet(0);

    public ActiveState() {
    }

    public ActiveState(String stateType, Set reports, Set invoices, Set users, Set products) {
       this.stateType = stateType;
       this.reports = reports;
       this.invoices = invoices;
       this.users = users;
       this.products = products;
    }
   
    public Integer getIdactiveState() {
        return this.idactiveState;
    }
    
    public void setIdactiveState(Integer idactiveState) {
        this.idactiveState = idactiveState;
    }
    public String getStateType() {
        return this.stateType;
    }
    
    public void setStateType(String stateType) {
        this.stateType = stateType;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


