package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * Advertisment generated by hbm2java
 */
public class Advertisment  implements java.io.Serializable {


     private Integer idAdvertisment;
     private Product product;
     private Integer positionId;

    public Advertisment() {
    }

	
    public Advertisment(Product product) {
        this.product = product;
    }
    public Advertisment(Product product, Integer positionId) {
       this.product = product;
       this.positionId = positionId;
    }
   
    public Integer getIdAdvertisment() {
        return this.idAdvertisment;
    }
    
    public void setIdAdvertisment(Integer idAdvertisment) {
        this.idAdvertisment = idAdvertisment;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getPositionId() {
        return this.positionId;
    }
    
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }




}


