package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * CartReg generated by hbm2java
 */
public class CartReg  implements java.io.Serializable {


     private Integer idcartReg;
     private Product product;
     private User user;
     private String qty;

    public CartReg() {
    }

	
    public CartReg(Product product, User user) {
        this.product = product;
        this.user = user;
    }
    public CartReg(Product product, User user, String qty) {
       this.product = product;
       this.user = user;
       this.qty = qty;
    }
   
    public Integer getIdcartReg() {
        return this.idcartReg;
    }
    
    public void setIdcartReg(Integer idcartReg) {
        this.idcartReg = idcartReg;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }




}


