package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distric generated by hbm2java
 */
public class Distric  implements java.io.Serializable {


     private Integer idDistric;
     private Province province;
     private String distric;
     private Double diliveryCost;
     private Set adresses = new HashSet(0);
     private Set invoices = new HashSet(0);

    public Distric() {
    }

	
    public Distric(Province province) {
        this.province = province;
    }
    public Distric(Province province, String distric, Double diliveryCost, Set adresses, Set invoices) {
       this.province = province;
       this.distric = distric;
       this.diliveryCost = diliveryCost;
       this.adresses = adresses;
       this.invoices = invoices;
    }
   
    public Integer getIdDistric() {
        return this.idDistric;
    }
    
    public void setIdDistric(Integer idDistric) {
        this.idDistric = idDistric;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getDistric() {
        return this.distric;
    }
    
    public void setDistric(String distric) {
        this.distric = distric;
    }
    public Double getDiliveryCost() {
        return this.diliveryCost;
    }
    
    public void setDiliveryCost(Double diliveryCost) {
        this.diliveryCost = diliveryCost;
    }
    public Set getAdresses() {
        return this.adresses;
    }
    
    public void setAdresses(Set adresses) {
        this.adresses = adresses;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


