package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * GrnReg generated by hbm2java
 */
public class GrnReg  implements java.io.Serializable {


     private Integer idGrnReg;
     private Grn grn;
     private Product product;
     private Integer qty;
     private Double price;

    public GrnReg() {
    }

	
    public GrnReg(Grn grn, Product product) {
        this.grn = grn;
        this.product = product;
    }
    public GrnReg(Grn grn, Product product, Integer qty, Double price) {
       this.grn = grn;
       this.product = product;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getIdGrnReg() {
        return this.idGrnReg;
    }
    
    public void setIdGrnReg(Integer idGrnReg) {
        this.idGrnReg = idGrnReg;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


