package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private int idimages;
     private Product product;
     private String path;

    public Images() {
    }

	
    public Images(int idimages, Product product) {
        this.idimages = idimages;
        this.product = product;
    }
    public Images(int idimages, Product product, String path) {
       this.idimages = idimages;
       this.product = product;
       this.path = path;
    }
   
    public int getIdimages() {
        return this.idimages;
    }
    
    public void setIdimages(int idimages) {
        this.idimages = idimages;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


