package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * InvoiceReg generated by hbm2java
 */
public class InvoiceReg  implements java.io.Serializable {


     private Integer idinvoiceReg;
     private Invoice invoice;
     private Product product;
     private Integer qty;
     private Double price;

    public InvoiceReg() {
    }

	
    public InvoiceReg(Invoice invoice, Product product) {
        this.invoice = invoice;
        this.product = product;
    }
    public InvoiceReg(Invoice invoice, Product product, Integer qty, Double price) {
       this.invoice = invoice;
       this.product = product;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getIdinvoiceReg() {
        return this.idinvoiceReg;
    }
    
    public void setIdinvoiceReg(Integer idinvoiceReg) {
        this.idinvoiceReg = idinvoiceReg;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


