package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int idorder;
     private Product product;
     private User user;
     private Integer qty;

    public Order() {
    }

	
    public Order(int idorder, Product product, User user) {
        this.idorder = idorder;
        this.product = product;
        this.user = user;
    }
    public Order(int idorder, Product product, User user, Integer qty) {
       this.idorder = idorder;
       this.product = product;
       this.user = user;
       this.qty = qty;
    }
   
    public int getIdorder() {
        return this.idorder;
    }
    
    public void setIdorder(int idorder) {
        this.idorder = idorder;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


