package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private ActiveState activeState;
     private Category category;
     private String product;
     private String discription;
     private String paketWeight;
     private String image;
     private String warenty;
     private Double buyingPrice;
     private Double sellingPrice;
     private Integer qty;
     private Set cartRegs = new HashSet(0);
     private Set invoiceRegs = new HashSet(0);
     private Set reports = new HashSet(0);
     private Set advertisments = new HashSet(0);
     private Set grnRegs = new HashSet(0);
     private Set orders = new HashSet(0);
     private Set imageses = new HashSet(0);

    public Product() {
    }

	
    public Product(ActiveState activeState, Category category) {
        this.activeState = activeState;
        this.category = category;
    }
    public Product(ActiveState activeState, Category category, String product, String discription, String paketWeight, String image, String warenty, Double buyingPrice, Double sellingPrice, Integer qty, Set cartRegs, Set invoiceRegs, Set reports, Set advertisments, Set grnRegs, Set orders, Set imageses) {
       this.activeState = activeState;
       this.category = category;
       this.product = product;
       this.discription = discription;
       this.paketWeight = paketWeight;
       this.image = image;
       this.warenty = warenty;
       this.buyingPrice = buyingPrice;
       this.sellingPrice = sellingPrice;
       this.qty = qty;
       this.cartRegs = cartRegs;
       this.invoiceRegs = invoiceRegs;
       this.reports = reports;
       this.advertisments = advertisments;
       this.grnRegs = grnRegs;
       this.orders = orders;
       this.imageses = imageses;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public ActiveState getActiveState() {
        return this.activeState;
    }
    
    public void setActiveState(ActiveState activeState) {
        this.activeState = activeState;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public String getPaketWeight() {
        return this.paketWeight;
    }
    
    public void setPaketWeight(String paketWeight) {
        this.paketWeight = paketWeight;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getWarenty() {
        return this.warenty;
    }
    
    public void setWarenty(String warenty) {
        this.warenty = warenty;
    }
    public Double getBuyingPrice() {
        return this.buyingPrice;
    }
    
    public void setBuyingPrice(Double buyingPrice) {
        this.buyingPrice = buyingPrice;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Set getCartRegs() {
        return this.cartRegs;
    }
    
    public void setCartRegs(Set cartRegs) {
        this.cartRegs = cartRegs;
    }
    public Set getInvoiceRegs() {
        return this.invoiceRegs;
    }
    
    public void setInvoiceRegs(Set invoiceRegs) {
        this.invoiceRegs = invoiceRegs;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }
    public Set getAdvertisments() {
        return this.advertisments;
    }
    
    public void setAdvertisments(Set advertisments) {
        this.advertisments = advertisments;
    }
    public Set getGrnRegs() {
        return this.grnRegs;
    }
    
    public void setGrnRegs(Set grnRegs) {
        this.grnRegs = grnRegs;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }




}


