package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private Integer idReport;
     private ActiveState activeState;
     private Invoice invoice;
     private Product product;
     private User user;
     private String reason;
     private String description;
     private String reply;

    public Report() {
    }

	
    public Report(ActiveState activeState, Invoice invoice, Product product, User user) {
        this.activeState = activeState;
        this.invoice = invoice;
        this.product = product;
        this.user = user;
    }
    public Report(ActiveState activeState, Invoice invoice, Product product, User user, String reason, String description, String reply) {
       this.activeState = activeState;
       this.invoice = invoice;
       this.product = product;
       this.user = user;
       this.reason = reason;
       this.description = description;
       this.reply = reply;
    }
   
    public Integer getIdReport() {
        return this.idReport;
    }
    
    public void setIdReport(Integer idReport) {
        this.idReport = idReport;
    }
    public ActiveState getActiveState() {
        return this.activeState;
    }
    
    public void setActiveState(ActiveState activeState) {
        this.activeState = activeState;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }




}


