package DB;
// Generated Dec 5, 2016 9:43:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer iduserType;
     private String userType;
     private Set users = new HashSet(0);

    public UserType() {
    }

    public UserType(String userType, Set users) {
       this.userType = userType;
       this.users = users;
    }
   
    public Integer getIduserType() {
        return this.iduserType;
    }
    
    public void setIduserType(Integer iduserType) {
        this.iduserType = iduserType;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


